#ifndef RVB_SPEC_MMAP_H
#define RVB_SPEC_MMAP_H

/* Generated by tools/mmapgen.py. Do not edit. */

/* Reusable decode type layouts. */

/* boot_rom */
#define RVB_BOOT_ROM_SIZE 0x00001000

/* mtimer */
#define RVB_MTIMER_SIZE 0x00000008

/* mtimecmp */
#define RVB_MTIMECMP_SIZE 0x00007ff8

/* mswi */
#define RVB_MSWI_SIZE 0x00004000

/* sswi */
#define RVB_SSWI_SIZE 0x00004000

/* mtime_ctrl */
#define RVB_MTIME_CTRL_SIZE 0x00001000

/* plic */
#define RVB_PLIC_SIZE 0x00400000

/* uart */
#define RVB_UART_SIZE 0x00000010

/* gpio */
#define RVB_GPIO_SIZE 0x00000010

/* gtimer */
#define RVB_GTIMER_SIZE 0x00000010

/* pcm */
#define RVB_PCM_SIZE 0x00001000

/* sysctrl */
#define RVB_SYSCTRL_SIZE 0x00001000

/* sdspi */
#define RVB_SDSPI_SIZE 0x00001000

/* eth */
#define RVB_ETH_SIZE 0x00001000

/* ddr */
#define RVB_DDR_SIZE 0x40000000

/* flash */
#define RVB_FLASH_SIZE 0x02000000

/* aclint */
#define RVB_ACLINT_SIZE 0x00100000
#define RVB_ACLINT_MTIMER_OFFSET 0x00000000
#define RVB_ACLINT_MTIMECMP_OFFSET 0x00010000
#define RVB_ACLINT_MSWI_OFFSET 0x00020000
#define RVB_ACLINT_SSWI_OFFSET 0x00030000
#define RVB_ACLINT_MTIME_CTRL_OFFSET 0x00040000

/* peri */
#define RVB_PERI_SIZE 0x00100000
#define RVB_PERI_UART_OFFSET 0x00000000
#define RVB_PERI_GPIO_OFFSET 0x00001000
#define RVB_PERI_GTIMER_OFFSET 0x00002000
#define RVB_PERI_PCM_OFFSET 0x00003000
#define RVB_PERI_SYSCTRL_OFFSET 0x00004000

/* io */
#define RVB_IO_SIZE 0x00100000
#define RVB_IO_SDSPI_OFFSET 0x00000000
#define RVB_IO_ETH_OFFSET 0x00001000

/* cfg */
#define RVB_CFG_SIZE 0x02000000
#define RVB_CFG_PERI_OFFSET 0x00000000
#define RVB_CFG_IO_OFFSET 0x00100000
#define RVB_CFG_ACLINT_OFFSET 0x01000000
#define RVB_CFG_PLIC_OFFSET 0x01100000

/* mm */
#define RVB_MM_SIZE 0x80000000
#define RVB_MM_DDR_OFFSET 0x00000000
#define RVB_MM_FLASH_OFFSET 0x40000000

/* mmap */
#define RVB_MMAP_SIZE 0x100000000
#define RVB_MMAP_BOOT_ROM_OFFSET 0x00000000
#define RVB_MMAP_CFG_OFFSET 0x30000000
#define RVB_MMAP_MM_OFFSET 0x40000000

/* Concrete instance bases expanded from mmap. */

/* boot_rom: boot_rom */
#define RVB_BOOT_ROM_BASE 0x00000000

/* cfg: cfg */
#define RVB_CFG_BASE 0x30000000

/* cfg.peri: peri */
#define RVB_PERI_BASE 0x30000000

/* cfg.peri.uart: uart */
#define RVB_UART_BASE 0x30000000

/* cfg.peri.gpio: gpio */
#define RVB_GPIO_BASE 0x30001000

/* cfg.peri.gtimer: gtimer */
#define RVB_GTIMER_BASE 0x30002000

/* cfg.peri.pcm: pcm */
#define RVB_PCM_BASE 0x30003000

/* cfg.peri.sysctrl: sysctrl */
#define RVB_SYSCTRL_BASE 0x30004000

/* cfg.io: io */
#define RVB_IO_BASE 0x30100000

/* cfg.io.sdspi: sdspi */
#define RVB_SDSPI_BASE 0x30100000

/* cfg.io.eth: eth */
#define RVB_ETH_BASE 0x30101000

/* cfg.aclint: aclint */
#define RVB_ACLINT_BASE 0x31000000

/* cfg.aclint.mtimer: mtimer */
#define RVB_MTIMER_BASE 0x31000000

/* cfg.aclint.mtimecmp: mtimecmp */
#define RVB_MTIMECMP_BASE 0x31010000

/* cfg.aclint.mswi: mswi */
#define RVB_MSWI_BASE 0x31020000

/* cfg.aclint.sswi: sswi */
#define RVB_SSWI_BASE 0x31030000

/* cfg.aclint.mtime_ctrl: mtime_ctrl */
#define RVB_MTIME_CTRL_BASE 0x31040000

/* cfg.plic: plic */
#define RVB_PLIC_BASE 0x31100000

/* mm: mm */
#define RVB_MM_BASE 0x40000000

/* mm.ddr: ddr */
#define RVB_DDR_BASE 0x40000000

/* mm.flash: flash */
#define RVB_FLASH_BASE 0x80000000

#endif /* RVB_SPEC_MMAP_H */
