#ifndef RVB_REGS_C_ETH_H
#define RVB_REGS_C_ETH_H

/* Generated by tools/reggen.py. Do not edit. */

/* version register, offset: 0x00000000 */
#define RVB_ETH_VERSION_REG_OFFSET 0x00000000
#define RVB_ETH_VERSION_REG_RESET 0x00010000
#define RVB_ETH_VERSION_REG_MASK 0xffffffff
#define RVB_ETH_VERSION_REG_VALUE_SHIFT 0
#define RVB_ETH_VERSION_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_VERSION_REG_VALUE_RESET 0x00010000

/* cap register, offset: 0x00000004 */
#define RVB_ETH_CAP_REG_OFFSET 0x00000004
#define RVB_ETH_CAP_REG_RESET 0x06000007
#define RVB_ETH_CAP_REG_MASK 0xffff0007
#define RVB_ETH_CAP_REG_DMA_SHIFT 0
#define RVB_ETH_CAP_REG_DMA_MASK 0x00000001
#define RVB_ETH_CAP_REG_DMA_RESET 0x00000001
#define RVB_ETH_CAP_REG_RING_SHIFT 1
#define RVB_ETH_CAP_REG_RING_MASK 0x00000002
#define RVB_ETH_CAP_REG_RING_RESET 0x00000001
#define RVB_ETH_CAP_REG_MDIO_SHIFT 2
#define RVB_ETH_CAP_REG_MDIO_MASK 0x00000004
#define RVB_ETH_CAP_REG_MDIO_RESET 0x00000001
#define RVB_ETH_CAP_REG_MAX_FRAME_SHIFT 16
#define RVB_ETH_CAP_REG_MAX_FRAME_MASK 0xffff0000
#define RVB_ETH_CAP_REG_MAX_FRAME_RESET 0x00000600

/* ctrl register, offset: 0x00000008 */
#define RVB_ETH_CTRL_REG_OFFSET 0x00000008
#define RVB_ETH_CTRL_REG_RESET 0x00000000
#define RVB_ETH_CTRL_REG_MASK 0x80000003
#define RVB_ETH_CTRL_REG_ENABLE_SHIFT 0
#define RVB_ETH_CTRL_REG_ENABLE_MASK 0x00000001
#define RVB_ETH_CTRL_REG_ENABLE_RESET 0x00000000
#define RVB_ETH_CTRL_REG_PROMISC_SHIFT 1
#define RVB_ETH_CTRL_REG_PROMISC_MASK 0x00000002
#define RVB_ETH_CTRL_REG_PROMISC_RESET 0x00000000
#define RVB_ETH_CTRL_REG_SW_RESET_SHIFT 31
#define RVB_ETH_CTRL_REG_SW_RESET_MASK 0x80000000
#define RVB_ETH_CTRL_REG_SW_RESET_RESET 0x00000000

/* status register, offset: 0x0000000c */
#define RVB_ETH_STATUS_REG_OFFSET 0x0000000c
#define RVB_ETH_STATUS_REG_RESET 0x00000060
#define RVB_ETH_STATUS_REG_MASK 0x0000007f
#define RVB_ETH_STATUS_REG_ENABLED_SHIFT 0
#define RVB_ETH_STATUS_REG_ENABLED_MASK 0x00000001
#define RVB_ETH_STATUS_REG_ENABLED_RESET 0x00000000
#define RVB_ETH_STATUS_REG_LINK_UP_SHIFT 1
#define RVB_ETH_STATUS_REG_LINK_UP_MASK 0x00000002
#define RVB_ETH_STATUS_REG_LINK_UP_RESET 0x00000000
#define RVB_ETH_STATUS_REG_TX_BUSY_SHIFT 2
#define RVB_ETH_STATUS_REG_TX_BUSY_MASK 0x00000004
#define RVB_ETH_STATUS_REG_TX_BUSY_RESET 0x00000000
#define RVB_ETH_STATUS_REG_RX_BUSY_SHIFT 3
#define RVB_ETH_STATUS_REG_RX_BUSY_MASK 0x00000008
#define RVB_ETH_STATUS_REG_RX_BUSY_RESET 0x00000000
#define RVB_ETH_STATUS_REG_SPEED_SHIFT 4
#define RVB_ETH_STATUS_REG_SPEED_MASK 0x00000030
#define RVB_ETH_STATUS_REG_SPEED_RESET 0x00000002
#define RVB_ETH_STATUS_REG_FULL_DUPLEX_SHIFT 6
#define RVB_ETH_STATUS_REG_FULL_DUPLEX_MASK 0x00000040
#define RVB_ETH_STATUS_REG_FULL_DUPLEX_RESET 0x00000001

/* mac_lo register, offset: 0x00000010 */
#define RVB_ETH_MAC_LO_REG_OFFSET 0x00000010
#define RVB_ETH_MAC_LO_REG_RESET 0x00000002
#define RVB_ETH_MAC_LO_REG_MASK 0xffffffff
#define RVB_ETH_MAC_LO_REG_VALUE_SHIFT 0
#define RVB_ETH_MAC_LO_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_MAC_LO_REG_VALUE_RESET 0x00000002

/* mac_hi register, offset: 0x00000014 */
#define RVB_ETH_MAC_HI_REG_OFFSET 0x00000014
#define RVB_ETH_MAC_HI_REG_RESET 0x00000100
#define RVB_ETH_MAC_HI_REG_MASK 0x0000ffff
#define RVB_ETH_MAC_HI_REG_VALUE_SHIFT 0
#define RVB_ETH_MAC_HI_REG_VALUE_MASK 0x0000ffff
#define RVB_ETH_MAC_HI_REG_VALUE_RESET 0x00000100

/* max_frame register, offset: 0x00000018 */
#define RVB_ETH_MAX_FRAME_REG_OFFSET 0x00000018
#define RVB_ETH_MAX_FRAME_REG_RESET 0x00000600
#define RVB_ETH_MAX_FRAME_REG_MASK 0xffffffff
#define RVB_ETH_MAX_FRAME_REG_VALUE_SHIFT 0
#define RVB_ETH_MAX_FRAME_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_MAX_FRAME_REG_VALUE_RESET 0x00000600

/* reserved_1c register, offset: 0x0000001c */
#define RVB_ETH_RESERVED_1C_REG_OFFSET 0x0000001c
#define RVB_ETH_RESERVED_1C_REG_RESET 0x00000000
#define RVB_ETH_RESERVED_1C_REG_MASK 0xffffffff
#define RVB_ETH_RESERVED_1C_REG_VALUE_SHIFT 0
#define RVB_ETH_RESERVED_1C_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_RESERVED_1C_REG_VALUE_RESET 0x00000000

/* tx_desc_base register, offset: 0x00000020 */
#define RVB_ETH_TX_DESC_BASE_REG_OFFSET 0x00000020
#define RVB_ETH_TX_DESC_BASE_REG_RESET 0x00000000
#define RVB_ETH_TX_DESC_BASE_REG_MASK 0xffffffff
#define RVB_ETH_TX_DESC_BASE_REG_VALUE_SHIFT 0
#define RVB_ETH_TX_DESC_BASE_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_TX_DESC_BASE_REG_VALUE_RESET 0x00000000

/* tx_ring_size register, offset: 0x00000024 */
#define RVB_ETH_TX_RING_SIZE_REG_OFFSET 0x00000024
#define RVB_ETH_TX_RING_SIZE_REG_RESET 0x00000000
#define RVB_ETH_TX_RING_SIZE_REG_MASK 0xffffffff
#define RVB_ETH_TX_RING_SIZE_REG_VALUE_SHIFT 0
#define RVB_ETH_TX_RING_SIZE_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_TX_RING_SIZE_REG_VALUE_RESET 0x00000000

/* tx_tail register, offset: 0x00000028 */
#define RVB_ETH_TX_TAIL_REG_OFFSET 0x00000028
#define RVB_ETH_TX_TAIL_REG_RESET 0x00000000
#define RVB_ETH_TX_TAIL_REG_MASK 0xffffffff
#define RVB_ETH_TX_TAIL_REG_VALUE_SHIFT 0
#define RVB_ETH_TX_TAIL_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_TX_TAIL_REG_VALUE_RESET 0x00000000

/* tx_head register, offset: 0x0000002c */
#define RVB_ETH_TX_HEAD_REG_OFFSET 0x0000002c
#define RVB_ETH_TX_HEAD_REG_RESET 0x00000000
#define RVB_ETH_TX_HEAD_REG_MASK 0xffffffff
#define RVB_ETH_TX_HEAD_REG_VALUE_SHIFT 0
#define RVB_ETH_TX_HEAD_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_TX_HEAD_REG_VALUE_RESET 0x00000000

/* rx_desc_base register, offset: 0x00000030 */
#define RVB_ETH_RX_DESC_BASE_REG_OFFSET 0x00000030
#define RVB_ETH_RX_DESC_BASE_REG_RESET 0x00000000
#define RVB_ETH_RX_DESC_BASE_REG_MASK 0xffffffff
#define RVB_ETH_RX_DESC_BASE_REG_VALUE_SHIFT 0
#define RVB_ETH_RX_DESC_BASE_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_RX_DESC_BASE_REG_VALUE_RESET 0x00000000

/* rx_ring_size register, offset: 0x00000034 */
#define RVB_ETH_RX_RING_SIZE_REG_OFFSET 0x00000034
#define RVB_ETH_RX_RING_SIZE_REG_RESET 0x00000000
#define RVB_ETH_RX_RING_SIZE_REG_MASK 0xffffffff
#define RVB_ETH_RX_RING_SIZE_REG_VALUE_SHIFT 0
#define RVB_ETH_RX_RING_SIZE_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_RX_RING_SIZE_REG_VALUE_RESET 0x00000000

/* rx_tail register, offset: 0x00000038 */
#define RVB_ETH_RX_TAIL_REG_OFFSET 0x00000038
#define RVB_ETH_RX_TAIL_REG_RESET 0x00000000
#define RVB_ETH_RX_TAIL_REG_MASK 0xffffffff
#define RVB_ETH_RX_TAIL_REG_VALUE_SHIFT 0
#define RVB_ETH_RX_TAIL_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_RX_TAIL_REG_VALUE_RESET 0x00000000

/* rx_head register, offset: 0x0000003c */
#define RVB_ETH_RX_HEAD_REG_OFFSET 0x0000003c
#define RVB_ETH_RX_HEAD_REG_RESET 0x00000000
#define RVB_ETH_RX_HEAD_REG_MASK 0xffffffff
#define RVB_ETH_RX_HEAD_REG_VALUE_SHIFT 0
#define RVB_ETH_RX_HEAD_REG_VALUE_MASK 0xffffffff
#define RVB_ETH_RX_HEAD_REG_VALUE_RESET 0x00000000

/* irq_status register, offset: 0x00000040 */
#define RVB_ETH_IRQ_STATUS_REG_OFFSET 0x00000040
#define RVB_ETH_IRQ_STATUS_REG_RESET 0x00000000
#define RVB_ETH_IRQ_STATUS_REG_MASK 0x0000001f
#define RVB_ETH_IRQ_STATUS_REG_TX_SHIFT 0
#define RVB_ETH_IRQ_STATUS_REG_TX_MASK 0x00000001
#define RVB_ETH_IRQ_STATUS_REG_TX_RESET 0x00000000
#define RVB_ETH_IRQ_STATUS_REG_RX_SHIFT 1
#define RVB_ETH_IRQ_STATUS_REG_RX_MASK 0x00000002
#define RVB_ETH_IRQ_STATUS_REG_RX_RESET 0x00000000
#define RVB_ETH_IRQ_STATUS_REG_LINK_SHIFT 2
#define RVB_ETH_IRQ_STATUS_REG_LINK_MASK 0x00000004
#define RVB_ETH_IRQ_STATUS_REG_LINK_RESET 0x00000000
#define RVB_ETH_IRQ_STATUS_REG_RX_DROP_SHIFT 3
#define RVB_ETH_IRQ_STATUS_REG_RX_DROP_MASK 0x00000008
#define RVB_ETH_IRQ_STATUS_REG_RX_DROP_RESET 0x00000000
#define RVB_ETH_IRQ_STATUS_REG_ERROR_SHIFT 4
#define RVB_ETH_IRQ_STATUS_REG_ERROR_MASK 0x00000010
#define RVB_ETH_IRQ_STATUS_REG_ERROR_RESET 0x00000000

/* irq_enable register, offset: 0x00000044 */
#define RVB_ETH_IRQ_ENABLE_REG_OFFSET 0x00000044
#define RVB_ETH_IRQ_ENABLE_REG_RESET 0x00000000
#define RVB_ETH_IRQ_ENABLE_REG_MASK 0x0000001f
#define RVB_ETH_IRQ_ENABLE_REG_TX_SHIFT 0
#define RVB_ETH_IRQ_ENABLE_REG_TX_MASK 0x00000001
#define RVB_ETH_IRQ_ENABLE_REG_TX_RESET 0x00000000
#define RVB_ETH_IRQ_ENABLE_REG_RX_SHIFT 1
#define RVB_ETH_IRQ_ENABLE_REG_RX_MASK 0x00000002
#define RVB_ETH_IRQ_ENABLE_REG_RX_RESET 0x00000000
#define RVB_ETH_IRQ_ENABLE_REG_LINK_SHIFT 2
#define RVB_ETH_IRQ_ENABLE_REG_LINK_MASK 0x00000004
#define RVB_ETH_IRQ_ENABLE_REG_LINK_RESET 0x00000000
#define RVB_ETH_IRQ_ENABLE_REG_RX_DROP_SHIFT 3
#define RVB_ETH_IRQ_ENABLE_REG_RX_DROP_MASK 0x00000008
#define RVB_ETH_IRQ_ENABLE_REG_RX_DROP_RESET 0x00000000
#define RVB_ETH_IRQ_ENABLE_REG_ERROR_SHIFT 4
#define RVB_ETH_IRQ_ENABLE_REG_ERROR_MASK 0x00000010
#define RVB_ETH_IRQ_ENABLE_REG_ERROR_RESET 0x00000000

/* rx_drop register, offset: 0x00000048 */
#define RVB_ETH_RX_DROP_REG_OFFSET 0x00000048
#define RVB_ETH_RX_DROP_REG_RESET 0x00000000
#define RVB_ETH_RX_DROP_REG_MASK 0xffffffff
#define RVB_ETH_RX_DROP_REG_COUNT_SHIFT 0
#define RVB_ETH_RX_DROP_REG_COUNT_MASK 0xffffffff
#define RVB_ETH_RX_DROP_REG_COUNT_RESET 0x00000000

/* tx_packets register, offset: 0x0000004c */
#define RVB_ETH_TX_PACKETS_REG_OFFSET 0x0000004c
#define RVB_ETH_TX_PACKETS_REG_RESET 0x00000000
#define RVB_ETH_TX_PACKETS_REG_MASK 0xffffffff
#define RVB_ETH_TX_PACKETS_REG_COUNT_SHIFT 0
#define RVB_ETH_TX_PACKETS_REG_COUNT_MASK 0xffffffff
#define RVB_ETH_TX_PACKETS_REG_COUNT_RESET 0x00000000

/* rx_packets register, offset: 0x00000050 */
#define RVB_ETH_RX_PACKETS_REG_OFFSET 0x00000050
#define RVB_ETH_RX_PACKETS_REG_RESET 0x00000000
#define RVB_ETH_RX_PACKETS_REG_MASK 0xffffffff
#define RVB_ETH_RX_PACKETS_REG_COUNT_SHIFT 0
#define RVB_ETH_RX_PACKETS_REG_COUNT_MASK 0xffffffff
#define RVB_ETH_RX_PACKETS_REG_COUNT_RESET 0x00000000

/* mdio_cmd register, offset: 0x00000054 */
#define RVB_ETH_MDIO_CMD_REG_OFFSET 0x00000054
#define RVB_ETH_MDIO_CMD_REG_RESET 0x00000000
#define RVB_ETH_MDIO_CMD_REG_MASK 0xc0001f1f
#define RVB_ETH_MDIO_CMD_REG_PHY_ADDR_SHIFT 0
#define RVB_ETH_MDIO_CMD_REG_PHY_ADDR_MASK 0x0000001f
#define RVB_ETH_MDIO_CMD_REG_PHY_ADDR_RESET 0x00000000
#define RVB_ETH_MDIO_CMD_REG_REG_ADDR_SHIFT 8
#define RVB_ETH_MDIO_CMD_REG_REG_ADDR_MASK 0x00001f00
#define RVB_ETH_MDIO_CMD_REG_REG_ADDR_RESET 0x00000000
#define RVB_ETH_MDIO_CMD_REG_WRITE_SHIFT 30
#define RVB_ETH_MDIO_CMD_REG_WRITE_MASK 0x40000000
#define RVB_ETH_MDIO_CMD_REG_WRITE_RESET 0x00000000
#define RVB_ETH_MDIO_CMD_REG_START_SHIFT 31
#define RVB_ETH_MDIO_CMD_REG_START_MASK 0x80000000
#define RVB_ETH_MDIO_CMD_REG_START_RESET 0x00000000

/* mdio_data register, offset: 0x00000058 */
#define RVB_ETH_MDIO_DATA_REG_OFFSET 0x00000058
#define RVB_ETH_MDIO_DATA_REG_RESET 0x00000000
#define RVB_ETH_MDIO_DATA_REG_MASK 0x0000ffff
#define RVB_ETH_MDIO_DATA_REG_VALUE_SHIFT 0
#define RVB_ETH_MDIO_DATA_REG_VALUE_MASK 0x0000ffff
#define RVB_ETH_MDIO_DATA_REG_VALUE_RESET 0x00000000

/* mdio_status register, offset: 0x0000005c */
#define RVB_ETH_MDIO_STATUS_REG_OFFSET 0x0000005c
#define RVB_ETH_MDIO_STATUS_REG_RESET 0x00000000
#define RVB_ETH_MDIO_STATUS_REG_MASK 0x00000007
#define RVB_ETH_MDIO_STATUS_REG_BUSY_SHIFT 0
#define RVB_ETH_MDIO_STATUS_REG_BUSY_MASK 0x00000001
#define RVB_ETH_MDIO_STATUS_REG_BUSY_RESET 0x00000000
#define RVB_ETH_MDIO_STATUS_REG_DONE_SHIFT 1
#define RVB_ETH_MDIO_STATUS_REG_DONE_MASK 0x00000002
#define RVB_ETH_MDIO_STATUS_REG_DONE_RESET 0x00000000
#define RVB_ETH_MDIO_STATUS_REG_ERROR_SHIFT 2
#define RVB_ETH_MDIO_STATUS_REG_ERROR_MASK 0x00000004
#define RVB_ETH_MDIO_STATUS_REG_ERROR_RESET 0x00000000

#ifndef __ASSEMBLER__
/* version register, offset: 0x00000000 */
typedef union rvb_eth_version_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_version_reg_t;

/* cap register, offset: 0x00000004 */
typedef union rvb_eth_cap_reg {
    u32 raw;
    struct {
        u32 dma : 1;
        u32 ring : 1;
        u32 mdio : 1;
        u32 rsvd_15_3 : 13;
        u32 max_frame : 16;
    } fields;
} rvb_eth_cap_reg_t;

/* ctrl register, offset: 0x00000008 */
typedef union rvb_eth_ctrl_reg {
    u32 raw;
    struct {
        u32 enable : 1;
        u32 promisc : 1;
        u32 rsvd_30_2 : 29;
        u32 sw_reset : 1;
    } fields;
} rvb_eth_ctrl_reg_t;

/* status register, offset: 0x0000000c */
typedef enum rvb_eth_status_reg_speed {
    RVB_ETH_STATUS_REG_SPEED_MBPS10 = 0x00000000,
    RVB_ETH_STATUS_REG_SPEED_MBPS100 = 0x00000001,
    RVB_ETH_STATUS_REG_SPEED_MBPS1000 = 0x00000002,
} rvb_eth_status_reg_speed_t;

typedef union rvb_eth_status_reg {
    u32 raw;
    struct {
        u32 enabled : 1;
        u32 link_up : 1;
        u32 tx_busy : 1;
        u32 rx_busy : 1;
        u32 speed : 2;
        u32 full_duplex : 1;
        u32 rsvd_31_7 : 25;
    } fields;
} rvb_eth_status_reg_t;

/* mac_lo register, offset: 0x00000010 */
typedef union rvb_eth_mac_lo_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_mac_lo_reg_t;

/* mac_hi register, offset: 0x00000014 */
typedef union rvb_eth_mac_hi_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_eth_mac_hi_reg_t;

/* max_frame register, offset: 0x00000018 */
typedef union rvb_eth_max_frame_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_max_frame_reg_t;

/* reserved_1c register, offset: 0x0000001c */
typedef union rvb_eth_reserved_1c_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_reserved_1c_reg_t;

/* tx_desc_base register, offset: 0x00000020 */
typedef union rvb_eth_tx_desc_base_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_tx_desc_base_reg_t;

/* tx_ring_size register, offset: 0x00000024 */
typedef union rvb_eth_tx_ring_size_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_tx_ring_size_reg_t;

/* tx_tail register, offset: 0x00000028 */
typedef union rvb_eth_tx_tail_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_tx_tail_reg_t;

/* tx_head register, offset: 0x0000002c */
typedef union rvb_eth_tx_head_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_tx_head_reg_t;

/* rx_desc_base register, offset: 0x00000030 */
typedef union rvb_eth_rx_desc_base_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_rx_desc_base_reg_t;

/* rx_ring_size register, offset: 0x00000034 */
typedef union rvb_eth_rx_ring_size_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_rx_ring_size_reg_t;

/* rx_tail register, offset: 0x00000038 */
typedef union rvb_eth_rx_tail_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_rx_tail_reg_t;

/* rx_head register, offset: 0x0000003c */
typedef union rvb_eth_rx_head_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_eth_rx_head_reg_t;

/* irq_status register, offset: 0x00000040 */
typedef union rvb_eth_irq_status_reg {
    u32 raw;
    struct {
        u32 tx : 1;
        u32 rx : 1;
        u32 link : 1;
        u32 rx_drop : 1;
        u32 error : 1;
        u32 rsvd_31_5 : 27;
    } fields;
} rvb_eth_irq_status_reg_t;

/* irq_enable register, offset: 0x00000044 */
typedef union rvb_eth_irq_enable_reg {
    u32 raw;
    struct {
        u32 tx : 1;
        u32 rx : 1;
        u32 link : 1;
        u32 rx_drop : 1;
        u32 error : 1;
        u32 rsvd_31_5 : 27;
    } fields;
} rvb_eth_irq_enable_reg_t;

/* rx_drop register, offset: 0x00000048 */
typedef union rvb_eth_rx_drop_reg {
    u32 raw;
    struct {
        u32 count : 32;
    } fields;
} rvb_eth_rx_drop_reg_t;

/* tx_packets register, offset: 0x0000004c */
typedef union rvb_eth_tx_packets_reg {
    u32 raw;
    struct {
        u32 count : 32;
    } fields;
} rvb_eth_tx_packets_reg_t;

/* rx_packets register, offset: 0x00000050 */
typedef union rvb_eth_rx_packets_reg {
    u32 raw;
    struct {
        u32 count : 32;
    } fields;
} rvb_eth_rx_packets_reg_t;

/* mdio_cmd register, offset: 0x00000054 */
typedef union rvb_eth_mdio_cmd_reg {
    u32 raw;
    struct {
        u32 phy_addr : 5;
        u32 rsvd_7_5 : 3;
        u32 reg_addr : 5;
        u32 rsvd_29_13 : 17;
        u32 write : 1;
        u32 start : 1;
    } fields;
} rvb_eth_mdio_cmd_reg_t;

/* mdio_data register, offset: 0x00000058 */
typedef union rvb_eth_mdio_data_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_eth_mdio_data_reg_t;

/* mdio_status register, offset: 0x0000005c */
typedef union rvb_eth_mdio_status_reg {
    u32 raw;
    struct {
        u32 busy : 1;
        u32 done : 1;
        u32 error : 1;
        u32 rsvd_31_3 : 29;
    } fields;
} rvb_eth_mdio_status_reg_t;

#endif

#endif /* RVB_REGS_C_ETH_H */
