#ifndef RVB_REGS_C_GPIO_H
#define RVB_REGS_C_GPIO_H

/* Generated by tools/reggen.py. Do not edit. */

/* out register, offset: 0x00000000 */
#define RVB_GPIO_OUT_REG_OFFSET 0x00000000
#define RVB_GPIO_OUT_REG_RESET 0x00000000
#define RVB_GPIO_OUT_REG_MASK 0x00ffffff
#define RVB_GPIO_OUT_REG_VALUE_SHIFT 0
#define RVB_GPIO_OUT_REG_VALUE_MASK 0x00ffffff
#define RVB_GPIO_OUT_REG_VALUE_RESET 0x00000000

/* mode_lo register, offset: 0x00000004 */
#define RVB_GPIO_MODE_LO_REG_OFFSET 0x00000004
#define RVB_GPIO_MODE_LO_REG_RESET 0x00000000
#define RVB_GPIO_MODE_LO_REG_MASK 0xffffffff
#define RVB_GPIO_MODE_LO_REG_MODES_SHIFT 0
#define RVB_GPIO_MODE_LO_REG_MODES_MASK 0xffffffff
#define RVB_GPIO_MODE_LO_REG_MODES_RESET 0x00000000

/* mode_hi register, offset: 0x00000008 */
#define RVB_GPIO_MODE_HI_REG_OFFSET 0x00000008
#define RVB_GPIO_MODE_HI_REG_RESET 0x00000000
#define RVB_GPIO_MODE_HI_REG_MASK 0x0000ffff
#define RVB_GPIO_MODE_HI_REG_MODES_SHIFT 0
#define RVB_GPIO_MODE_HI_REG_MODES_MASK 0x0000ffff
#define RVB_GPIO_MODE_HI_REG_MODES_RESET 0x00000000

#ifndef __ASSEMBLER__
typedef enum rvb_gpio_mode {
    RVB_GPIO_MODE_OUTPUT = 0x00000000,
    RVB_GPIO_MODE_INPUT = 0x00000001,
    RVB_GPIO_MODE_INPUT_IRQ = 0x00000002,
    RVB_GPIO_MODE_RESERVED = 0x00000003,
} rvb_gpio_mode_t;

/* out register, offset: 0x00000000 */
typedef union rvb_gpio_out_reg {
    u32 raw;
    struct {
        u32 value : 24;
        u32 rsvd_31_24 : 8;
    } fields;
} rvb_gpio_out_reg_t;

/* mode_lo register, offset: 0x00000004 */
typedef union rvb_gpio_mode_lo_reg {
    u32 raw;
    struct {
        u32 modes : 32;
    } fields;
} rvb_gpio_mode_lo_reg_t;

/* mode_hi register, offset: 0x00000008 */
typedef union rvb_gpio_mode_hi_reg {
    u32 raw;
    struct {
        u32 modes : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_gpio_mode_hi_reg_t;

#endif

#endif /* RVB_REGS_C_GPIO_H */
