#ifndef RVB_REGS_C_GTIMER_H
#define RVB_REGS_C_GTIMER_H

/* Generated by tools/gen/reggen.py. Do not edit. */

/* ctrl register, offset: 0x00000000 */
#define RVB_GTIMER_CTRL_REG_OFFSET 0x00000000
#define RVB_GTIMER_CTRL_REG_RESET 0x00000000
#define RVB_GTIMER_CTRL_REG_MASK 0x00000001
#define RVB_GTIMER_CTRL_REG_ENABLE_SHIFT 0
#define RVB_GTIMER_CTRL_REG_ENABLE_MASK 0x00000001
#define RVB_GTIMER_CTRL_REG_ENABLE_RESET 0x00000000

/* count register, offset: 0x00000004 */
#define RVB_GTIMER_COUNT_REG_OFFSET 0x00000004
#define RVB_GTIMER_COUNT_REG_RESET 0x00000000
#define RVB_GTIMER_COUNT_REG_MASK 0xffffffff
#define RVB_GTIMER_COUNT_REG_VALUE_SHIFT 0
#define RVB_GTIMER_COUNT_REG_VALUE_MASK 0xffffffff
#define RVB_GTIMER_COUNT_REG_VALUE_RESET 0x00000000

/* reload register, offset: 0x00000008 */
#define RVB_GTIMER_RELOAD_REG_OFFSET 0x00000008
#define RVB_GTIMER_RELOAD_REG_RESET 0x00000000
#define RVB_GTIMER_RELOAD_REG_MASK 0xffffffff
#define RVB_GTIMER_RELOAD_REG_VALUE_SHIFT 0
#define RVB_GTIMER_RELOAD_REG_VALUE_MASK 0xffffffff
#define RVB_GTIMER_RELOAD_REG_VALUE_RESET 0x00000000

/* irq register, offset: 0x0000000c */
#define RVB_GTIMER_IRQ_REG_OFFSET 0x0000000c
#define RVB_GTIMER_IRQ_REG_RESET 0x00000000
#define RVB_GTIMER_IRQ_REG_MASK 0x00000001
#define RVB_GTIMER_IRQ_REG_PENDING_SHIFT 0
#define RVB_GTIMER_IRQ_REG_PENDING_MASK 0x00000001
#define RVB_GTIMER_IRQ_REG_PENDING_RESET 0x00000000

#ifndef __ASSEMBLER__
/* ctrl register, offset: 0x00000000 */
typedef union rvb_gtimer_ctrl_reg {
    u32 raw;
    struct {
        u32 enable : 1;
        u32 rsvd_31_1 : 31;
    } fields;
} rvb_gtimer_ctrl_reg_t;

/* count register, offset: 0x00000004 */
typedef union rvb_gtimer_count_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_gtimer_count_reg_t;

/* reload register, offset: 0x00000008 */
typedef union rvb_gtimer_reload_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_gtimer_reload_reg_t;

/* irq register, offset: 0x0000000c */
typedef union rvb_gtimer_irq_reg {
    u32 raw;
    struct {
        u32 pending : 1;
        u32 rsvd_31_1 : 31;
    } fields;
} rvb_gtimer_irq_reg_t;

typedef struct rvb_gtimer_regs {
    rvb_gtimer_ctrl_reg_t ctrl;
    rvb_gtimer_count_reg_t count;
    rvb_gtimer_reload_reg_t reload;
    rvb_gtimer_irq_reg_t irq;
} rvb_gtimer_regs_t;

#endif

#endif /* RVB_REGS_C_GTIMER_H */
