#ifndef RVB_REGS_C_PCM_SAMPLE_H
#define RVB_REGS_C_PCM_SAMPLE_H

/* Generated by tools/gen/reggen.py. Do not edit. */

/* version register, offset: 0x00000000 */
#define RVB_PCM_SAMPLE_VERSION_REG_OFFSET 0x00000000
#define RVB_PCM_SAMPLE_VERSION_REG_RESET 0x00010000
#define RVB_PCM_SAMPLE_VERSION_REG_MASK 0xffffffff
#define RVB_PCM_SAMPLE_VERSION_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_VERSION_REG_VALUE_MASK 0xffffffff
#define RVB_PCM_SAMPLE_VERSION_REG_VALUE_RESET 0x00010000

/* cap register, offset: 0x00000004 */
#define RVB_PCM_SAMPLE_CAP_REG_OFFSET 0x00000004
#define RVB_PCM_SAMPLE_CAP_REG_RESET 0x80000013
#define RVB_PCM_SAMPLE_CAP_REG_MASK 0xffff003f
#define RVB_PCM_SAMPLE_CAP_REG_AUTO_SAMPLE_SHIFT 0
#define RVB_PCM_SAMPLE_CAP_REG_AUTO_SAMPLE_MASK 0x00000001
#define RVB_PCM_SAMPLE_CAP_REG_AUTO_SAMPLE_RESET 0x00000001
#define RVB_PCM_SAMPLE_CAP_REG_DMA_SHIFT 1
#define RVB_PCM_SAMPLE_CAP_REG_DMA_MASK 0x00000002
#define RVB_PCM_SAMPLE_CAP_REG_DMA_RESET 0x00000001
#define RVB_PCM_SAMPLE_CAP_REG_MAX_OUTSTANDING_SHIFT 2
#define RVB_PCM_SAMPLE_CAP_REG_MAX_OUTSTANDING_MASK 0x0000003c
#define RVB_PCM_SAMPLE_CAP_REG_MAX_OUTSTANDING_RESET 0x00000004
#define RVB_PCM_SAMPLE_CAP_REG_MAX_ENTRIES_SHIFT 16
#define RVB_PCM_SAMPLE_CAP_REG_MAX_ENTRIES_MASK 0xffff0000
#define RVB_PCM_SAMPLE_CAP_REG_MAX_ENTRIES_RESET 0x00008000

/* control register, offset: 0x00000008 */
#define RVB_PCM_SAMPLE_CONTROL_REG_OFFSET 0x00000008
#define RVB_PCM_SAMPLE_CONTROL_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_CONTROL_REG_MASK 0x00000003
#define RVB_PCM_SAMPLE_CONTROL_REG_START_SHIFT 0
#define RVB_PCM_SAMPLE_CONTROL_REG_START_MASK 0x00000001
#define RVB_PCM_SAMPLE_CONTROL_REG_START_RESET 0x00000000
#define RVB_PCM_SAMPLE_CONTROL_REG_STOP_SHIFT 1
#define RVB_PCM_SAMPLE_CONTROL_REG_STOP_MASK 0x00000002
#define RVB_PCM_SAMPLE_CONTROL_REG_STOP_RESET 0x00000000

/* status register, offset: 0x0000000c */
#define RVB_PCM_SAMPLE_STATUS_REG_OFFSET 0x0000000c
#define RVB_PCM_SAMPLE_STATUS_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_STATUS_REG_MASK 0x0000001f
#define RVB_PCM_SAMPLE_STATUS_REG_RUNNING_SHIFT 0
#define RVB_PCM_SAMPLE_STATUS_REG_RUNNING_MASK 0x00000001
#define RVB_PCM_SAMPLE_STATUS_REG_RUNNING_RESET 0x00000000
#define RVB_PCM_SAMPLE_STATUS_REG_BUSY_SHIFT 1
#define RVB_PCM_SAMPLE_STATUS_REG_BUSY_MASK 0x00000002
#define RVB_PCM_SAMPLE_STATUS_REG_BUSY_RESET 0x00000000
#define RVB_PCM_SAMPLE_STATUS_REG_RING_FULL_SHIFT 2
#define RVB_PCM_SAMPLE_STATUS_REG_RING_FULL_MASK 0x00000004
#define RVB_PCM_SAMPLE_STATUS_REG_RING_FULL_RESET 0x00000000
#define RVB_PCM_SAMPLE_STATUS_REG_SAMPLE_LATE_SHIFT 3
#define RVB_PCM_SAMPLE_STATUS_REG_SAMPLE_LATE_MASK 0x00000008
#define RVB_PCM_SAMPLE_STATUS_REG_SAMPLE_LATE_RESET 0x00000000
#define RVB_PCM_SAMPLE_STATUS_REG_DMA_ERROR_SHIFT 4
#define RVB_PCM_SAMPLE_STATUS_REG_DMA_ERROR_MASK 0x00000010
#define RVB_PCM_SAMPLE_STATUS_REG_DMA_ERROR_RESET 0x00000000

/* sample_period register, offset: 0x00000010 */
#define RVB_PCM_SAMPLE_SAMPLE_PERIOD_REG_OFFSET 0x00000010
#define RVB_PCM_SAMPLE_SAMPLE_PERIOD_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_SAMPLE_PERIOD_REG_MASK 0xffffffff
#define RVB_PCM_SAMPLE_SAMPLE_PERIOD_REG_CYCLES_SHIFT 0
#define RVB_PCM_SAMPLE_SAMPLE_PERIOD_REG_CYCLES_MASK 0xffffffff
#define RVB_PCM_SAMPLE_SAMPLE_PERIOD_REG_CYCLES_RESET 0x00000000

/* timestamp_period register, offset: 0x00000014 */
#define RVB_PCM_SAMPLE_TIMESTAMP_PERIOD_REG_OFFSET 0x00000014
#define RVB_PCM_SAMPLE_TIMESTAMP_PERIOD_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_TIMESTAMP_PERIOD_REG_MASK 0xffffffff
#define RVB_PCM_SAMPLE_TIMESTAMP_PERIOD_REG_CYCLES_SHIFT 0
#define RVB_PCM_SAMPLE_TIMESTAMP_PERIOD_REG_CYCLES_MASK 0xffffffff
#define RVB_PCM_SAMPLE_TIMESTAMP_PERIOD_REG_CYCLES_RESET 0x00000000

/* ring_base register, offset: 0x00000018 */
#define RVB_PCM_SAMPLE_RING_BASE_REG_OFFSET 0x00000018
#define RVB_PCM_SAMPLE_RING_BASE_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_RING_BASE_REG_MASK 0xffffffff
#define RVB_PCM_SAMPLE_RING_BASE_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_RING_BASE_REG_VALUE_MASK 0xffffffff
#define RVB_PCM_SAMPLE_RING_BASE_REG_VALUE_RESET 0x00000000

/* ring_entries register, offset: 0x0000001c */
#define RVB_PCM_SAMPLE_RING_ENTRIES_REG_OFFSET 0x0000001c
#define RVB_PCM_SAMPLE_RING_ENTRIES_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_RING_ENTRIES_REG_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_RING_ENTRIES_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_RING_ENTRIES_REG_VALUE_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_RING_ENTRIES_REG_VALUE_RESET 0x00000000

/* rptr register, offset: 0x00000020 */
#define RVB_PCM_SAMPLE_RPTR_REG_OFFSET 0x00000020
#define RVB_PCM_SAMPLE_RPTR_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_RPTR_REG_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_RPTR_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_RPTR_REG_VALUE_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_RPTR_REG_VALUE_RESET 0x00000000

/* wptr register, offset: 0x00000024 */
#define RVB_PCM_SAMPLE_WPTR_REG_OFFSET 0x00000024
#define RVB_PCM_SAMPLE_WPTR_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_WPTR_REG_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_WPTR_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_WPTR_REG_VALUE_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_WPTR_REG_VALUE_RESET 0x00000000

/* record_size register, offset: 0x00000028 */
#define RVB_PCM_SAMPLE_RECORD_SIZE_REG_OFFSET 0x00000028
#define RVB_PCM_SAMPLE_RECORD_SIZE_REG_RESET 0x00000800
#define RVB_PCM_SAMPLE_RECORD_SIZE_REG_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_RECORD_SIZE_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_RECORD_SIZE_REG_VALUE_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_RECORD_SIZE_REG_VALUE_RESET 0x00000800

/* timestamp_lo register, offset: 0x0000002c */
#define RVB_PCM_SAMPLE_TIMESTAMP_LO_REG_OFFSET 0x0000002c
#define RVB_PCM_SAMPLE_TIMESTAMP_LO_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_TIMESTAMP_LO_REG_MASK 0xffffffff
#define RVB_PCM_SAMPLE_TIMESTAMP_LO_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_TIMESTAMP_LO_REG_VALUE_MASK 0xffffffff
#define RVB_PCM_SAMPLE_TIMESTAMP_LO_REG_VALUE_RESET 0x00000000

/* timestamp_hi register, offset: 0x00000030 */
#define RVB_PCM_SAMPLE_TIMESTAMP_HI_REG_OFFSET 0x00000030
#define RVB_PCM_SAMPLE_TIMESTAMP_HI_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_TIMESTAMP_HI_REG_MASK 0xffffffff
#define RVB_PCM_SAMPLE_TIMESTAMP_HI_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_TIMESTAMP_HI_REG_VALUE_MASK 0xffffffff
#define RVB_PCM_SAMPLE_TIMESTAMP_HI_REG_VALUE_RESET 0x00000000

/* error_info register, offset: 0x00000034 */
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_OFFSET 0x00000034
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_MASK 0x0000ff03
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_AXI_RESP_SHIFT 0
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_AXI_RESP_MASK 0x00000003
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_AXI_RESP_RESET 0x00000000
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_BURST_INDEX_SHIFT 8
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_BURST_INDEX_MASK 0x0000ff00
#define RVB_PCM_SAMPLE_ERROR_INFO_REG_BURST_INDEX_RESET 0x00000000

/* irq_threshold register, offset: 0x00000038 */
#define RVB_PCM_SAMPLE_IRQ_THRESHOLD_REG_OFFSET 0x00000038
#define RVB_PCM_SAMPLE_IRQ_THRESHOLD_REG_RESET 0x00000000
#define RVB_PCM_SAMPLE_IRQ_THRESHOLD_REG_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_IRQ_THRESHOLD_REG_VALUE_SHIFT 0
#define RVB_PCM_SAMPLE_IRQ_THRESHOLD_REG_VALUE_MASK 0x0000ffff
#define RVB_PCM_SAMPLE_IRQ_THRESHOLD_REG_VALUE_RESET 0x00000000

#ifndef __ASSEMBLER__
/* version register, offset: 0x00000000 */
typedef union rvb_pcm_sample_version_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_pcm_sample_version_reg_t;

/* cap register, offset: 0x00000004 */
typedef union rvb_pcm_sample_cap_reg {
    u32 raw;
    struct {
        u32 auto_sample : 1;
        u32 dma : 1;
        u32 max_outstanding : 4;
        u32 rsvd_15_6 : 10;
        u32 max_entries : 16;
    } fields;
} rvb_pcm_sample_cap_reg_t;

/* control register, offset: 0x00000008 */
typedef union rvb_pcm_sample_control_reg {
    u32 raw;
    struct {
        u32 start : 1;
        u32 stop : 1;
        u32 rsvd_31_2 : 30;
    } fields;
} rvb_pcm_sample_control_reg_t;

/* status register, offset: 0x0000000c */
typedef union rvb_pcm_sample_status_reg {
    u32 raw;
    struct {
        u32 running : 1;
        u32 busy : 1;
        u32 ring_full : 1;
        u32 sample_late : 1;
        u32 dma_error : 1;
        u32 rsvd_31_5 : 27;
    } fields;
} rvb_pcm_sample_status_reg_t;

/* sample_period register, offset: 0x00000010 */
typedef union rvb_pcm_sample_sample_period_reg {
    u32 raw;
    struct {
        u32 cycles : 32;
    } fields;
} rvb_pcm_sample_sample_period_reg_t;

/* timestamp_period register, offset: 0x00000014 */
typedef union rvb_pcm_sample_timestamp_period_reg {
    u32 raw;
    struct {
        u32 cycles : 32;
    } fields;
} rvb_pcm_sample_timestamp_period_reg_t;

/* ring_base register, offset: 0x00000018 */
typedef union rvb_pcm_sample_ring_base_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_pcm_sample_ring_base_reg_t;

/* ring_entries register, offset: 0x0000001c */
typedef union rvb_pcm_sample_ring_entries_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_pcm_sample_ring_entries_reg_t;

/* rptr register, offset: 0x00000020 */
typedef union rvb_pcm_sample_rptr_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_pcm_sample_rptr_reg_t;

/* wptr register, offset: 0x00000024 */
typedef union rvb_pcm_sample_wptr_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_pcm_sample_wptr_reg_t;

/* record_size register, offset: 0x00000028 */
typedef union rvb_pcm_sample_record_size_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_pcm_sample_record_size_reg_t;

/* timestamp_lo register, offset: 0x0000002c */
typedef union rvb_pcm_sample_timestamp_lo_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_pcm_sample_timestamp_lo_reg_t;

/* timestamp_hi register, offset: 0x00000030 */
typedef union rvb_pcm_sample_timestamp_hi_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_pcm_sample_timestamp_hi_reg_t;

/* error_info register, offset: 0x00000034 */
typedef union rvb_pcm_sample_error_info_reg {
    u32 raw;
    struct {
        u32 axi_resp : 2;
        u32 rsvd_7_2 : 6;
        u32 burst_index : 8;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_pcm_sample_error_info_reg_t;

/* irq_threshold register, offset: 0x00000038 */
typedef union rvb_pcm_sample_irq_threshold_reg {
    u32 raw;
    struct {
        u32 value : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_pcm_sample_irq_threshold_reg_t;

typedef struct rvb_pcm_sample_regs {
    rvb_pcm_sample_version_reg_t version;
    rvb_pcm_sample_cap_reg_t cap;
    rvb_pcm_sample_control_reg_t control;
    rvb_pcm_sample_status_reg_t status;
    rvb_pcm_sample_sample_period_reg_t sample_period;
    rvb_pcm_sample_timestamp_period_reg_t timestamp_period;
    rvb_pcm_sample_ring_base_reg_t ring_base;
    rvb_pcm_sample_ring_entries_reg_t ring_entries;
    rvb_pcm_sample_rptr_reg_t rptr;
    rvb_pcm_sample_wptr_reg_t wptr;
    rvb_pcm_sample_record_size_reg_t record_size;
    rvb_pcm_sample_timestamp_lo_reg_t timestamp_lo;
    rvb_pcm_sample_timestamp_hi_reg_t timestamp_hi;
    rvb_pcm_sample_error_info_reg_t error_info;
    rvb_pcm_sample_irq_threshold_reg_t irq_threshold;
} rvb_pcm_sample_regs_t;

#endif

#endif /* RVB_REGS_C_PCM_SAMPLE_H */
