#ifndef RVB_REGS_C_SDSPI_H
#define RVB_REGS_C_SDSPI_H

/* Generated by tools/gen/reggen.py. Do not edit. */

/* version register, offset: 0x00000000 */
#define RVB_SDSPI_VERSION_REG_OFFSET 0x00000000
#define RVB_SDSPI_VERSION_REG_RESET 0x00010000
#define RVB_SDSPI_VERSION_REG_MASK 0xffffffff
#define RVB_SDSPI_VERSION_REG_VALUE_SHIFT 0
#define RVB_SDSPI_VERSION_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_VERSION_REG_VALUE_RESET 0x00010000

/* cap register, offset: 0x00000004 */
#define RVB_SDSPI_CAP_REG_OFFSET 0x00000004
#define RVB_SDSPI_CAP_REG_RESET 0x00800003
#define RVB_SDSPI_CAP_REG_MASK 0xffff0003
#define RVB_SDSPI_CAP_REG_SPI_MODE_SHIFT 0
#define RVB_SDSPI_CAP_REG_SPI_MODE_MASK 0x00000001
#define RVB_SDSPI_CAP_REG_SPI_MODE_RESET 0x00000001
#define RVB_SDSPI_CAP_REG_DMA_SHIFT 1
#define RVB_SDSPI_CAP_REG_DMA_MASK 0x00000002
#define RVB_SDSPI_CAP_REG_DMA_RESET 0x00000001
#define RVB_SDSPI_CAP_REG_MAX_BLOCKS_SHIFT 16
#define RVB_SDSPI_CAP_REG_MAX_BLOCKS_MASK 0xffff0000
#define RVB_SDSPI_CAP_REG_MAX_BLOCKS_RESET 0x00000080

/* ctrl register, offset: 0x00000008 */
#define RVB_SDSPI_CTRL_REG_OFFSET 0x00000008
#define RVB_SDSPI_CTRL_REG_RESET 0x00000000
#define RVB_SDSPI_CTRL_REG_MASK 0x00000003
#define RVB_SDSPI_CTRL_REG_ENABLE_SHIFT 0
#define RVB_SDSPI_CTRL_REG_ENABLE_MASK 0x00000001
#define RVB_SDSPI_CTRL_REG_ENABLE_RESET 0x00000000
#define RVB_SDSPI_CTRL_REG_SW_RESET_SHIFT 1
#define RVB_SDSPI_CTRL_REG_SW_RESET_MASK 0x00000002
#define RVB_SDSPI_CTRL_REG_SW_RESET_RESET 0x00000000

/* clock register, offset: 0x0000000c */
#define RVB_SDSPI_CLOCK_REG_OFFSET 0x0000000c
#define RVB_SDSPI_CLOCK_REG_RESET 0x00000000
#define RVB_SDSPI_CLOCK_REG_MASK 0xffffffff
#define RVB_SDSPI_CLOCK_REG_DIVIDER_SHIFT 0
#define RVB_SDSPI_CLOCK_REG_DIVIDER_MASK 0xffffffff
#define RVB_SDSPI_CLOCK_REG_DIVIDER_RESET 0x00000000

/* status register, offset: 0x00000010 */
#define RVB_SDSPI_STATUS_REG_OFFSET 0x00000010
#define RVB_SDSPI_STATUS_REG_RESET 0x00000008
#define RVB_SDSPI_STATUS_REG_MASK 0x0000000f
#define RVB_SDSPI_STATUS_REG_CARD_PRESENT_SHIFT 0
#define RVB_SDSPI_STATUS_REG_CARD_PRESENT_MASK 0x00000001
#define RVB_SDSPI_STATUS_REG_CARD_PRESENT_RESET 0x00000000
#define RVB_SDSPI_STATUS_REG_CARD_RO_SHIFT 1
#define RVB_SDSPI_STATUS_REG_CARD_RO_MASK 0x00000002
#define RVB_SDSPI_STATUS_REG_CARD_RO_RESET 0x00000000
#define RVB_SDSPI_STATUS_REG_BUSY_SHIFT 2
#define RVB_SDSPI_STATUS_REG_BUSY_MASK 0x00000004
#define RVB_SDSPI_STATUS_REG_BUSY_RESET 0x00000000
#define RVB_SDSPI_STATUS_REG_CARD_IDLE_SHIFT 3
#define RVB_SDSPI_STATUS_REG_CARD_IDLE_MASK 0x00000008
#define RVB_SDSPI_STATUS_REG_CARD_IDLE_RESET 0x00000001

/* cmd_arg register, offset: 0x00000014 */
#define RVB_SDSPI_CMD_ARG_REG_OFFSET 0x00000014
#define RVB_SDSPI_CMD_ARG_REG_RESET 0x00000000
#define RVB_SDSPI_CMD_ARG_REG_MASK 0xffffffff
#define RVB_SDSPI_CMD_ARG_REG_VALUE_SHIFT 0
#define RVB_SDSPI_CMD_ARG_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_CMD_ARG_REG_VALUE_RESET 0x00000000

/* cmd_ctrl register, offset: 0x00000018 */
#define RVB_SDSPI_CMD_CTRL_REG_OFFSET 0x00000018
#define RVB_SDSPI_CMD_CTRL_REG_RESET 0x00000000
#define RVB_SDSPI_CMD_CTRL_REG_MASK 0x8000373f
#define RVB_SDSPI_CMD_CTRL_REG_OPCODE_SHIFT 0
#define RVB_SDSPI_CMD_CTRL_REG_OPCODE_MASK 0x0000003f
#define RVB_SDSPI_CMD_CTRL_REG_OPCODE_RESET 0x00000000
#define RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_SHIFT 8
#define RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_MASK 0x00000700
#define RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_RESET 0x00000000
#define RVB_SDSPI_CMD_CTRL_REG_DATA_SHIFT 12
#define RVB_SDSPI_CMD_CTRL_REG_DATA_MASK 0x00001000
#define RVB_SDSPI_CMD_CTRL_REG_DATA_RESET 0x00000000
#define RVB_SDSPI_CMD_CTRL_REG_WRITE_SHIFT 13
#define RVB_SDSPI_CMD_CTRL_REG_WRITE_MASK 0x00002000
#define RVB_SDSPI_CMD_CTRL_REG_WRITE_RESET 0x00000000
#define RVB_SDSPI_CMD_CTRL_REG_START_SHIFT 31
#define RVB_SDSPI_CMD_CTRL_REG_START_MASK 0x80000000
#define RVB_SDSPI_CMD_CTRL_REG_START_RESET 0x00000000

/* cmd_status register, offset: 0x0000001c */
#define RVB_SDSPI_CMD_STATUS_REG_OFFSET 0x0000001c
#define RVB_SDSPI_CMD_STATUS_REG_RESET 0x00000000
#define RVB_SDSPI_CMD_STATUS_REG_MASK 0x0000003f
#define RVB_SDSPI_CMD_STATUS_REG_DONE_SHIFT 0
#define RVB_SDSPI_CMD_STATUS_REG_DONE_MASK 0x00000001
#define RVB_SDSPI_CMD_STATUS_REG_DONE_RESET 0x00000000
#define RVB_SDSPI_CMD_STATUS_REG_ERROR_SHIFT 1
#define RVB_SDSPI_CMD_STATUS_REG_ERROR_MASK 0x00000002
#define RVB_SDSPI_CMD_STATUS_REG_ERROR_RESET 0x00000000
#define RVB_SDSPI_CMD_STATUS_REG_TIMEOUT_SHIFT 2
#define RVB_SDSPI_CMD_STATUS_REG_TIMEOUT_MASK 0x00000004
#define RVB_SDSPI_CMD_STATUS_REG_TIMEOUT_RESET 0x00000000
#define RVB_SDSPI_CMD_STATUS_REG_ILLEGAL_SHIFT 3
#define RVB_SDSPI_CMD_STATUS_REG_ILLEGAL_MASK 0x00000008
#define RVB_SDSPI_CMD_STATUS_REG_ILLEGAL_RESET 0x00000000
#define RVB_SDSPI_CMD_STATUS_REG_ADDRESS_SHIFT 4
#define RVB_SDSPI_CMD_STATUS_REG_ADDRESS_MASK 0x00000010
#define RVB_SDSPI_CMD_STATUS_REG_ADDRESS_RESET 0x00000000
#define RVB_SDSPI_CMD_STATUS_REG_PARAM_ERROR_SHIFT 5
#define RVB_SDSPI_CMD_STATUS_REG_PARAM_ERROR_MASK 0x00000020
#define RVB_SDSPI_CMD_STATUS_REG_PARAM_ERROR_RESET 0x00000000

/* resp0 register, offset: 0x00000020 */
#define RVB_SDSPI_RESP0_REG_OFFSET 0x00000020
#define RVB_SDSPI_RESP0_REG_RESET 0x00000000
#define RVB_SDSPI_RESP0_REG_MASK 0xffffffff
#define RVB_SDSPI_RESP0_REG_VALUE_SHIFT 0
#define RVB_SDSPI_RESP0_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_RESP0_REG_VALUE_RESET 0x00000000

/* resp1 register, offset: 0x00000024 */
#define RVB_SDSPI_RESP1_REG_OFFSET 0x00000024
#define RVB_SDSPI_RESP1_REG_RESET 0x00000000
#define RVB_SDSPI_RESP1_REG_MASK 0xffffffff
#define RVB_SDSPI_RESP1_REG_VALUE_SHIFT 0
#define RVB_SDSPI_RESP1_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_RESP1_REG_VALUE_RESET 0x00000000

/* dma_addr register, offset: 0x00000028 */
#define RVB_SDSPI_DMA_ADDR_REG_OFFSET 0x00000028
#define RVB_SDSPI_DMA_ADDR_REG_RESET 0x00000000
#define RVB_SDSPI_DMA_ADDR_REG_MASK 0xffffffff
#define RVB_SDSPI_DMA_ADDR_REG_VALUE_SHIFT 0
#define RVB_SDSPI_DMA_ADDR_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_DMA_ADDR_REG_VALUE_RESET 0x00000000

/* block_size register, offset: 0x0000002c */
#define RVB_SDSPI_BLOCK_SIZE_REG_OFFSET 0x0000002c
#define RVB_SDSPI_BLOCK_SIZE_REG_RESET 0x00000200
#define RVB_SDSPI_BLOCK_SIZE_REG_MASK 0xffffffff
#define RVB_SDSPI_BLOCK_SIZE_REG_VALUE_SHIFT 0
#define RVB_SDSPI_BLOCK_SIZE_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_BLOCK_SIZE_REG_VALUE_RESET 0x00000200

/* block_count register, offset: 0x00000030 */
#define RVB_SDSPI_BLOCK_COUNT_REG_OFFSET 0x00000030
#define RVB_SDSPI_BLOCK_COUNT_REG_RESET 0x00000001
#define RVB_SDSPI_BLOCK_COUNT_REG_MASK 0xffffffff
#define RVB_SDSPI_BLOCK_COUNT_REG_VALUE_SHIFT 0
#define RVB_SDSPI_BLOCK_COUNT_REG_VALUE_MASK 0xffffffff
#define RVB_SDSPI_BLOCK_COUNT_REG_VALUE_RESET 0x00000001

/* data_status register, offset: 0x00000034 */
#define RVB_SDSPI_DATA_STATUS_REG_OFFSET 0x00000034
#define RVB_SDSPI_DATA_STATUS_REG_RESET 0x00000000
#define RVB_SDSPI_DATA_STATUS_REG_MASK 0x0000000f
#define RVB_SDSPI_DATA_STATUS_REG_DONE_SHIFT 0
#define RVB_SDSPI_DATA_STATUS_REG_DONE_MASK 0x00000001
#define RVB_SDSPI_DATA_STATUS_REG_DONE_RESET 0x00000000
#define RVB_SDSPI_DATA_STATUS_REG_ERROR_SHIFT 1
#define RVB_SDSPI_DATA_STATUS_REG_ERROR_MASK 0x00000002
#define RVB_SDSPI_DATA_STATUS_REG_ERROR_RESET 0x00000000
#define RVB_SDSPI_DATA_STATUS_REG_AXI_ERROR_SHIFT 2
#define RVB_SDSPI_DATA_STATUS_REG_AXI_ERROR_MASK 0x00000004
#define RVB_SDSPI_DATA_STATUS_REG_AXI_ERROR_RESET 0x00000000
#define RVB_SDSPI_DATA_STATUS_REG_IO_ERROR_SHIFT 3
#define RVB_SDSPI_DATA_STATUS_REG_IO_ERROR_MASK 0x00000008
#define RVB_SDSPI_DATA_STATUS_REG_IO_ERROR_RESET 0x00000000

/* irq_status register, offset: 0x00000038 */
#define RVB_SDSPI_IRQ_STATUS_REG_OFFSET 0x00000038
#define RVB_SDSPI_IRQ_STATUS_REG_RESET 0x00000000
#define RVB_SDSPI_IRQ_STATUS_REG_MASK 0x0000000f
#define RVB_SDSPI_IRQ_STATUS_REG_CMD_DONE_SHIFT 0
#define RVB_SDSPI_IRQ_STATUS_REG_CMD_DONE_MASK 0x00000001
#define RVB_SDSPI_IRQ_STATUS_REG_CMD_DONE_RESET 0x00000000
#define RVB_SDSPI_IRQ_STATUS_REG_DATA_DONE_SHIFT 1
#define RVB_SDSPI_IRQ_STATUS_REG_DATA_DONE_MASK 0x00000002
#define RVB_SDSPI_IRQ_STATUS_REG_DATA_DONE_RESET 0x00000000
#define RVB_SDSPI_IRQ_STATUS_REG_ERROR_SHIFT 2
#define RVB_SDSPI_IRQ_STATUS_REG_ERROR_MASK 0x00000004
#define RVB_SDSPI_IRQ_STATUS_REG_ERROR_RESET 0x00000000
#define RVB_SDSPI_IRQ_STATUS_REG_CARD_CHANGE_SHIFT 3
#define RVB_SDSPI_IRQ_STATUS_REG_CARD_CHANGE_MASK 0x00000008
#define RVB_SDSPI_IRQ_STATUS_REG_CARD_CHANGE_RESET 0x00000000

/* irq_enable register, offset: 0x0000003c */
#define RVB_SDSPI_IRQ_ENABLE_REG_OFFSET 0x0000003c
#define RVB_SDSPI_IRQ_ENABLE_REG_RESET 0x00000000
#define RVB_SDSPI_IRQ_ENABLE_REG_MASK 0x0000000f
#define RVB_SDSPI_IRQ_ENABLE_REG_CMD_DONE_SHIFT 0
#define RVB_SDSPI_IRQ_ENABLE_REG_CMD_DONE_MASK 0x00000001
#define RVB_SDSPI_IRQ_ENABLE_REG_CMD_DONE_RESET 0x00000000
#define RVB_SDSPI_IRQ_ENABLE_REG_DATA_DONE_SHIFT 1
#define RVB_SDSPI_IRQ_ENABLE_REG_DATA_DONE_MASK 0x00000002
#define RVB_SDSPI_IRQ_ENABLE_REG_DATA_DONE_RESET 0x00000000
#define RVB_SDSPI_IRQ_ENABLE_REG_ERROR_SHIFT 2
#define RVB_SDSPI_IRQ_ENABLE_REG_ERROR_MASK 0x00000004
#define RVB_SDSPI_IRQ_ENABLE_REG_ERROR_RESET 0x00000000
#define RVB_SDSPI_IRQ_ENABLE_REG_CARD_CHANGE_SHIFT 3
#define RVB_SDSPI_IRQ_ENABLE_REG_CARD_CHANGE_MASK 0x00000008
#define RVB_SDSPI_IRQ_ENABLE_REG_CARD_CHANGE_RESET 0x00000000

#ifndef __ASSEMBLER__
/* version register, offset: 0x00000000 */
typedef union rvb_sdspi_version_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_version_reg_t;

/* cap register, offset: 0x00000004 */
typedef union rvb_sdspi_cap_reg {
    u32 raw;
    struct {
        u32 spi_mode : 1;
        u32 dma : 1;
        u32 rsvd_15_2 : 14;
        u32 max_blocks : 16;
    } fields;
} rvb_sdspi_cap_reg_t;

/* ctrl register, offset: 0x00000008 */
typedef union rvb_sdspi_ctrl_reg {
    u32 raw;
    struct {
        u32 enable : 1;
        u32 sw_reset : 1;
        u32 rsvd_31_2 : 30;
    } fields;
} rvb_sdspi_ctrl_reg_t;

/* clock register, offset: 0x0000000c */
typedef union rvb_sdspi_clock_reg {
    u32 raw;
    struct {
        u32 divider : 32;
    } fields;
} rvb_sdspi_clock_reg_t;

/* status register, offset: 0x00000010 */
typedef union rvb_sdspi_status_reg {
    u32 raw;
    struct {
        u32 card_present : 1;
        u32 card_ro : 1;
        u32 busy : 1;
        u32 card_idle : 1;
        u32 rsvd_31_4 : 28;
    } fields;
} rvb_sdspi_status_reg_t;

/* cmd_arg register, offset: 0x00000014 */
typedef union rvb_sdspi_cmd_arg_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_cmd_arg_reg_t;

/* cmd_ctrl register, offset: 0x00000018 */
typedef enum rvb_sdspi_cmd_ctrl_reg_rsp_type {
    RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_NONE = 0x00000000,
    RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_R1 = 0x00000001,
    RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_R1B = 0x00000002,
    RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_R2 = 0x00000003,
    RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_R3 = 0x00000004,
    RVB_SDSPI_CMD_CTRL_REG_RSP_TYPE_R7 = 0x00000005,
} rvb_sdspi_cmd_ctrl_reg_rsp_type_t;

typedef union rvb_sdspi_cmd_ctrl_reg {
    u32 raw;
    struct {
        u32 opcode : 6;
        u32 rsvd_7_6 : 2;
        u32 rsp_type : 3;
        u32 rsvd_11 : 1;
        u32 data : 1;
        u32 write : 1;
        u32 rsvd_30_14 : 17;
        u32 start : 1;
    } fields;
} rvb_sdspi_cmd_ctrl_reg_t;

/* cmd_status register, offset: 0x0000001c */
typedef union rvb_sdspi_cmd_status_reg {
    u32 raw;
    struct {
        u32 done : 1;
        u32 error : 1;
        u32 timeout : 1;
        u32 illegal : 1;
        u32 address : 1;
        u32 param_error : 1;
        u32 rsvd_31_6 : 26;
    } fields;
} rvb_sdspi_cmd_status_reg_t;

/* resp0 register, offset: 0x00000020 */
typedef union rvb_sdspi_resp0_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_resp0_reg_t;

/* resp1 register, offset: 0x00000024 */
typedef union rvb_sdspi_resp1_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_resp1_reg_t;

/* dma_addr register, offset: 0x00000028 */
typedef union rvb_sdspi_dma_addr_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_dma_addr_reg_t;

/* block_size register, offset: 0x0000002c */
typedef union rvb_sdspi_block_size_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_block_size_reg_t;

/* block_count register, offset: 0x00000030 */
typedef union rvb_sdspi_block_count_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sdspi_block_count_reg_t;

/* data_status register, offset: 0x00000034 */
typedef union rvb_sdspi_data_status_reg {
    u32 raw;
    struct {
        u32 done : 1;
        u32 error : 1;
        u32 axi_error : 1;
        u32 io_error : 1;
        u32 rsvd_31_4 : 28;
    } fields;
} rvb_sdspi_data_status_reg_t;

/* irq_status register, offset: 0x00000038 */
typedef union rvb_sdspi_irq_status_reg {
    u32 raw;
    struct {
        u32 cmd_done : 1;
        u32 data_done : 1;
        u32 error : 1;
        u32 card_change : 1;
        u32 rsvd_31_4 : 28;
    } fields;
} rvb_sdspi_irq_status_reg_t;

/* irq_enable register, offset: 0x0000003c */
typedef union rvb_sdspi_irq_enable_reg {
    u32 raw;
    struct {
        u32 cmd_done : 1;
        u32 data_done : 1;
        u32 error : 1;
        u32 card_change : 1;
        u32 rsvd_31_4 : 28;
    } fields;
} rvb_sdspi_irq_enable_reg_t;

typedef struct rvb_sdspi_regs {
    rvb_sdspi_version_reg_t version;
    rvb_sdspi_cap_reg_t cap;
    rvb_sdspi_ctrl_reg_t ctrl;
    rvb_sdspi_clock_reg_t clock;
    rvb_sdspi_status_reg_t status;
    rvb_sdspi_cmd_arg_reg_t cmd_arg;
    rvb_sdspi_cmd_ctrl_reg_t cmd_ctrl;
    rvb_sdspi_cmd_status_reg_t cmd_status;
    rvb_sdspi_resp0_reg_t resp0;
    rvb_sdspi_resp1_reg_t resp1;
    rvb_sdspi_dma_addr_reg_t dma_addr;
    rvb_sdspi_block_size_reg_t block_size;
    rvb_sdspi_block_count_reg_t block_count;
    rvb_sdspi_data_status_reg_t data_status;
    rvb_sdspi_irq_status_reg_t irq_status;
    rvb_sdspi_irq_enable_reg_t irq_enable;
} rvb_sdspi_regs_t;

#endif

#endif /* RVB_REGS_C_SDSPI_H */
