#ifndef RVB_REGS_C_SYSCTRL_H
#define RVB_REGS_C_SYSCTRL_H

/* Generated by tools/gen/reggen.py. Do not edit. */

/* reset_req register, offset: 0x00000000 */
#define RVB_SYSCTRL_RESET_REQ_REG_OFFSET 0x00000000
#define RVB_SYSCTRL_RESET_REQ_REG_RESET 0x00000000
#define RVB_SYSCTRL_RESET_REQ_REG_MASK 0xffffffff
#define RVB_SYSCTRL_RESET_REQ_REG_VALUE_SHIFT 0
#define RVB_SYSCTRL_RESET_REQ_REG_VALUE_MASK 0xffffffff
#define RVB_SYSCTRL_RESET_REQ_REG_VALUE_RESET 0x00000000

/* reset_cause register, offset: 0x00000004 */
#define RVB_SYSCTRL_RESET_CAUSE_REG_OFFSET 0x00000004
#define RVB_SYSCTRL_RESET_CAUSE_REG_RESET 0x00000001
#define RVB_SYSCTRL_RESET_CAUSE_REG_MASK 0x00000003
#define RVB_SYSCTRL_RESET_CAUSE_REG_REASON_SHIFT 0
#define RVB_SYSCTRL_RESET_CAUSE_REG_REASON_MASK 0x00000003
#define RVB_SYSCTRL_RESET_CAUSE_REG_REASON_RESET 0x00000001

/* pwr_mngm_req register, offset: 0x00000008 */
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_OFFSET 0x00000008
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_RESET 0x00000000
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_MASK 0x00000007
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_CMD_SHIFT 0
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_CMD_MASK 0x00000001
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_CMD_RESET 0x00000000
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_SHIFT 1
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_MASK 0x00000006
#define RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_RESET 0x00000000

#ifndef __ASSEMBLER__
/* reset_req register, offset: 0x00000000 */
typedef enum rvb_sysctrl_reset_req_reg_value {
    RVB_SYSCTRL_RESET_REQ_REG_VALUE_MAGIC = 0x52564252,
} rvb_sysctrl_reset_req_reg_value_t;

typedef union rvb_sysctrl_reset_req_reg {
    u32 raw;
    struct {
        u32 value : 32;
    } fields;
} rvb_sysctrl_reset_req_reg_t;

/* reset_cause register, offset: 0x00000004 */
typedef enum rvb_sysctrl_reset_cause_reg_reason {
    RVB_SYSCTRL_RESET_CAUSE_REG_REASON_POR = 0x00000001,
    RVB_SYSCTRL_RESET_CAUSE_REG_REASON_SW = 0x00000002,
} rvb_sysctrl_reset_cause_reg_reason_t;

typedef union rvb_sysctrl_reset_cause_reg {
    u32 raw;
    struct {
        u32 reason : 2;
        u32 rsvd_31_2 : 30;
    } fields;
} rvb_sysctrl_reset_cause_reg_t;

/* pwr_mngm_req register, offset: 0x00000008 */
typedef enum rvb_sysctrl_pwr_mngm_req_reg_cmd {
    RVB_SYSCTRL_PWR_MNGM_REQ_REG_CMD_POWEROFF = 0x00000001,
} rvb_sysctrl_pwr_mngm_req_reg_cmd_t;

typedef enum rvb_sysctrl_pwr_mngm_req_reg_arg {
    RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_NORMAL = 0x00000000,
    RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_SIM_TEST_PASS = 0x00000001,
    RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_SIM_TEST_FAIL = 0x00000002,
    RVB_SYSCTRL_PWR_MNGM_REQ_REG_ARG_RESERVED = 0x00000003,
} rvb_sysctrl_pwr_mngm_req_reg_arg_t;

typedef union rvb_sysctrl_pwr_mngm_req_reg {
    u32 raw;
    struct {
        u32 cmd : 1;
        u32 arg : 2;
        u32 rsvd_31_3 : 29;
    } fields;
} rvb_sysctrl_pwr_mngm_req_reg_t;

typedef struct rvb_sysctrl_regs {
    rvb_sysctrl_reset_req_reg_t reset_req;
    rvb_sysctrl_reset_cause_reg_t reset_cause;
    rvb_sysctrl_pwr_mngm_req_reg_t pwr_mngm_req;
} rvb_sysctrl_regs_t;

#endif

#endif /* RVB_REGS_C_SYSCTRL_H */
