#ifndef RVB_REGS_C_UART_H
#define RVB_REGS_C_UART_H

/* Generated by tools/gen/reggen.py. Do not edit. */

/* bc register, offset: 0x00000000 */
#define RVB_UART_BC_REG_OFFSET 0x00000000
#define RVB_UART_BC_REG_RESET 0x00000009
#define RVB_UART_BC_REG_MASK 0x0000ffff
#define RVB_UART_BC_REG_CYCLES_SHIFT 0
#define RVB_UART_BC_REG_CYCLES_MASK 0x0000ffff
#define RVB_UART_BC_REG_CYCLES_RESET 0x00000009

/* tx register, offset: 0x00000004 */
#define RVB_UART_TX_REG_OFFSET 0x00000004
#define RVB_UART_TX_REG_RESET 0x00000000
#define RVB_UART_TX_REG_MASK 0x000000ff
#define RVB_UART_TX_REG_DATA_SHIFT 0
#define RVB_UART_TX_REG_DATA_MASK 0x000000ff
#define RVB_UART_TX_REG_DATA_RESET 0x00000000

/* rx register, offset: 0x00000008 */
#define RVB_UART_RX_REG_OFFSET 0x00000008
#define RVB_UART_RX_REG_RESET 0x00000000
#define RVB_UART_RX_REG_MASK 0x000000ff
#define RVB_UART_RX_REG_DATA_SHIFT 0
#define RVB_UART_RX_REG_DATA_MASK 0x000000ff
#define RVB_UART_RX_REG_DATA_RESET 0x00000000

/* status register, offset: 0x0000000c */
#define RVB_UART_STATUS_REG_OFFSET 0x0000000c
#define RVB_UART_STATUS_REG_RESET 0x00000000
#define RVB_UART_STATUS_REG_MASK 0x00000003
#define RVB_UART_STATUS_REG_RX_VALID_SHIFT 0
#define RVB_UART_STATUS_REG_RX_VALID_MASK 0x00000001
#define RVB_UART_STATUS_REG_RX_VALID_RESET 0x00000000
#define RVB_UART_STATUS_REG_TX_PENDING_SHIFT 1
#define RVB_UART_STATUS_REG_TX_PENDING_MASK 0x00000002
#define RVB_UART_STATUS_REG_TX_PENDING_RESET 0x00000000

#ifndef __ASSEMBLER__
/* bc register, offset: 0x00000000 */
typedef union rvb_uart_bc_reg {
    u32 raw;
    struct {
        u32 cycles : 16;
        u32 rsvd_31_16 : 16;
    } fields;
} rvb_uart_bc_reg_t;

/* tx register, offset: 0x00000004 */
typedef union rvb_uart_tx_reg {
    u32 raw;
    struct {
        u32 data : 8;
        u32 rsvd_31_8 : 24;
    } fields;
} rvb_uart_tx_reg_t;

/* rx register, offset: 0x00000008 */
typedef union rvb_uart_rx_reg {
    u32 raw;
    struct {
        u32 data : 8;
        u32 rsvd_31_8 : 24;
    } fields;
} rvb_uart_rx_reg_t;

/* status register, offset: 0x0000000c */
typedef union rvb_uart_status_reg {
    u32 raw;
    struct {
        u32 rx_valid : 1;
        u32 tx_pending : 1;
        u32 rsvd_31_2 : 30;
    } fields;
} rvb_uart_status_reg_t;

typedef struct rvb_uart_regs {
    rvb_uart_bc_reg_t bc;
    rvb_uart_tx_reg_t tx;
    rvb_uart_rx_reg_t rx;
    rvb_uart_status_reg_t status;
} rvb_uart_regs_t;

#endif

#endif /* RVB_REGS_C_UART_H */
